### ISSUE TITLE
Attaching Errors while pulling request

### ISSUE THREAD

**Issue by rjbhayani** [bizhuka/aqo#2]
![image](https://user-images.githubusercontent.com/19501487/81100693-933f0280-8f2a-11ea-885d-f97c048a0170.png)

**Comment by bizhuka** [comment]
Hello
there are some problems in zabapgit related to SH fm extensions
please import the package the second time
the error should go away

let me know if you have any installation problems

**Comment by bizhuka** [comment]
From 30.04.2021 all SHs were deleted
No SHs based on internal tables
