### ISSUE TITLE
About get for values

### ISSUE THREAD

**Issue by lhdias** [bizhuka/aqo#4]
Good day sir
would you have an example of how to retrieve (get) the values of one or more ID registered in the solution?

**Comment by bizhuka** [comment]
Hello

usually in constructor you have to add 1 code line
``` abap
zcl_aqo_option=>create( io_data = me ).
```
it creates or reads values from option
all read-only attributes will be an option fields & they could be edited in ZAQO transaction

example
SE24->ZCL_AQO_TESTER

documentation
https://bizhuka.github.io/aqo/se24-zcl_aqo_tester/

if you understand russian there is also a manual
https://www.youtube.com/watch?v=PyuKsp2b-Q8
the manual is a little bit newer than the documentation in github.io https://bizhuka.github.io/aqo

**Comment by bizhuka** [comment]
close the issue if there is no other questions
